autopilot:
  stage: build
  image: baselinews/paradrone:platformio
  script:
    - cd autopilot
    - platformio lib update
    - platformio run
  cache:
    key: pio-deps
    paths:
      - .pio/libdeps

relay:
  stage: build
  image: baselinews/paradrone:platformio
  script:
    - cd remotecontrol
    - platformio lib update
    - platformio run
  cache:
    key: pio-deps
    paths:
      - .pio/libdeps
