autopilot:
  stage: build
  image: baselinews/paradrone:platformio
  script:
    - cd autopilot
    - pio lib update
    - pio run
  cache:
    key: pio-deps
    paths:
      - .pio/libdeps

autopilot-test:
  stage: test
  image: baselinews/paradrone:platformio
  script:
    - cd autopilot
    - pio lib update
    - pio test -e native
  cache:
    key: pio-deps
    paths:
      - .pio/libdeps

rc:
  stage: build
  image: baselinews/paradrone:platformio
  script:
    - cd remotecontrol
    - pio lib update
    - pio run
  cache:
    key: pio-deps
    paths:
      - .pio/libdeps

android:
  stage: build
  image: circleci/android:api-29
  script:
    - cd android
    - ./gradlew compileDebugSources

android-test:
  stage: test
  image: circleci/android:api-29
  script:
    - cd android
    - ./gradlew testDebugUnitTest

hardware:
  stage: build
  image: node:14-slim
  script:
    - cd hardware
    - npm i
    - npm run model
    - npm run print
    - npm run actuator
    - npm run autopilot
    - npm run battery
    - npm run remotecontrol
    - npm run spool

simulator:
  stage: build
  image: node:14-slim
  script:
    - cd simulator
    - npm i
    - npx tsc

simulator-lint:
  stage: test
  image: node:14-slim
  script:
    - cd simulator
    - npm i
    - npx tslint --project .
