autopilot:
  stage: build
  image: baselinews/paradrone:platformio
  script:
    - cd autopilot
    - pio lib update
    - pio run
  cache:
    key: pio-deps
    paths:
      - .pio/libdeps

autopilot-test:
  stage: test
  image: baselinews/paradrone:platformio
  script:
    - cd autopilot
    - pio lib update
    - pio test -e native
  cache:
    key: pio-deps
    paths:
      - .pio/libdeps

rc:
  stage: build
  image: baselinews/paradrone:platformio
  script:
    - cd remotecontrol
    - pio lib update
    - pio run
  cache:
    key: pio-deps
    paths:
      - .pio/libdeps
