default:
  image: baselinews/paradrone:platformio

build:
  stage: build
  script:
    - cd arduino
    - platformio lib update
    - platformio run
  cache:
    key: pio-deps
    paths:
      - .pio/libdeps
