#!/bin/bash

set -e

DRY=--dryrun

ROOT=$(dirname $(dirname -- "$(readlink -f -- "$BASH_SOURCE")"))

aws --profile paradrone s3 sync $DRY "$ROOT/website/html/" s3://paradr.one/

# aws s3 cp $DRY simulator/index.html s3://paradr.one/simulator/
